language: csharp
solution: "./src/Autofac.TypedFactories.sln"
install:
- travis_retry nuget restore -verbosity detailed -source "https://api.nuget.org/v3/index.json" "./src/Autofac.TypedFactories.sln"
script:
- xbuild "./src/Autofac.TypedFactories.sln"
